name: bantoo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  image_cropper: ^9.1.0
  share_plus: ^11.0.0
  open_file: ^3.5.10
  excel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_bantoo.png
    - assets/header_img.png
    - assets/dashboard_avatar.png
    - assets/icons/qris_example.png
    - assets/icons/qris.png
    - assets/icons/shopeepay.png
    - assets/icons/dana.png
    - assets/icons/gopay.png
    - assets/icons/bca.png
    - assets/icons/bri.png
    - assets/icons/mandiri.png
    - assets/illustrations/payment_success.png
    - assets/illustrations/payment_instruction.png
    - assets/bantoo_hands.png